# Generated by Django 4.2.4 on 2023-09-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('material', models.BooleanField(null=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
